spring:
  application:
    name: blogs
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
#    password: root2025
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 6006
  servlet:
    context-path: /blogs/